### ISSUE TITLE
installation error in python 3.8.1

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [mindsdb/lightwood#100]
The installation fails like this
`ERROR: Could not find a version that satisfies the requirement torch>=1.3.0 (from pyro-ppl>=0.4.1->lightwood) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3.0 (from pyro-ppl>=0.4.1->lightwood)`

**Comment by ZoranPandovski** [comment]
Hi @Karlheinzniebuhr and thanks for reporting the issue. Pytorch still doesn't [support](https://github.com/pytorch/pytorch/issues/21741) python 3.8 version, so please use another python 3.7.x version.

**Comment by Karlheinzniebuhr** [comment]
I've installed the latest torch version and it works just fine on python 3.8.1

**Comment by ZoranPandovski** [comment]
@Karlheinzniebuhr On windows10 with python3.8.1 version I am getting the same error that you report when installing torch. Can you please explain how did you installed it?

**Comment by Karlheinzniebuhr** [comment]
Sure,
`pip install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by George3d6** [comment]
Pytroch *should* have a new release "early this week" based on a few issues I read related to various topics. Will wait for those and hopefully the new updates will work with python 3.8.x

currently python 3.8 doesn't run mindsdb on linux either.

**Comment by stonebig** [comment]
isn't it released now ?

**Comment by George3d6** [comment]
Now supports python 3.8, support should also be present in the new release of mindsdb in circa 1 hour if all goes well.
