### ISSUE TITLE
Implement a RandomForest mixer

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#1005]
Having a random forest-based mixer would be a great option to LightGBM and the rest of the available mixers.

Ideally, this mixer will support both regression and classification tasks by calling `sklearn.ensemble.RandomForestRegressor` and `sklearn.ensemble.RandomForestClassifier`, respectively.

The PR should have unit and integration tests so that we can verify the mixer works correctly.

**Comment by jaredc07** [comment]
Hi, I would like to work on this.

**Comment by paxcema** [comment]
Closed via #1017 🚀
