### ISSUE TITLE
Improve "ETSMixer" documentation

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#1007]
This mixer currently inherits the docstring from the `sktime` mixer, which translates into duplicated docs :)

A simple, short description for the underlying forecasting algorithm would be good enough.

**Comment by viveknshah** [comment]
I can take a stab at this.

**Comment by viveknshah** [comment]
Could you share a few pointers on how I could tackle the same? I can see how the docu is being replicated into the inherited doc but not sure how are we looking to override the same and with what?

**Comment by paxcema** [comment]
Sure, adding a docstring to the `__init__` method of the `ETSMixer` class should be enough for the docs system to override/ignore the parents' docstring.

As for the content, no need to be super detailed. It would be enough to mention that this is inheriting from SkTime and setting the model class to the Exponential Smoothing family. We can point users to the parent docstring for information on each individual argument.
