### ISSUE TITLE
Improve "Unit" mixer documentation

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#1009]
We don't have a docstring for this mixer. The challenge here is to eloquently describe what this mixer does (hint: it can be used when encoders themselves are the models, e.g. pretrained language models that receive a single column as input).

**Comment by 12-malak** [comment]
@paxcema I would like to work on this. Please assign me.

**Comment by ancatoza** [comment]
Hi, I think this haven't been solve yet, Can I help ?

**Comment by paxcema** [comment]
Hi @ancatoza, absolutely! I've assigned you. If you need any help please let us know either here or in the community slack.

**Comment by paxcema** [comment]
Closing via #1204.
