### ISSUE TITLE
🔧 Add library version to predictors

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#1010]
## What?

This issue is pretty simple: we should document what was the exact Lightwood version that was used to create every predictor object.

## How?

You can get the `lightwood.__version__` and add it to the predictor generation code in the `code_from_json_ai()` method inside `lightwood/api/json_ai.py`.

**Comment by adripo** [comment]
Hi @paxcema, can you have a look at my pr? I am not sure that my solution is correct and I am not able to test it.

**Comment by paxcema** [comment]
Yes, but let's give @adripo a full week before calling it (so, if he doesn't update in 4 days from now, I will reassign it to you).

**Comment by adripo** [comment]
@paxcema sorry I was was busy for the past few days. I will work this issue today.
