### ISSUE TITLE
Cannot install on python 3.10

### ISSUE THREAD

**Issue by Enforcer007** [mindsdb/lightwood#1012]
## Your Environment
* Python version: 3.10
* Operating system: Ubuntu
* Lightwood version: 22.9.1.0

## Describe your issue

Cannot install the lightwood on python 3.10.

One of the dependency `sktime >=0.11.0,<0.12.0` doesn't support 3.10 yet.

**Comment by ZoranPandovski** [comment]
Yes, some of the Lightwood dependencies are not supporting Python 3.10 version. Maybe we need to point in the docs that we support  Python versions >=3.7, < 3.10
