### ISSUE TITLE
Benchmark RandomForest vs LightGBM mixer

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#1029]
If RF is anywhere near LightGBM in accuracy, we should move to it as the default option and mark LGBM as unstable given some potential issues we've been experiencing lately.

**Comment by ErdoganSeref** [comment]
Could we use this [benchmark](https://mljar.com/machine-learning/lightgbm-vs-random-forest/)?

**Comment by paxcema** [comment]
Hey! Sadly, no. Lightwood does automated data pre-processing (cleaning, splitting, etc.) plus feature engineering, which is not covered by the above benchmark. It is a good data point to have though (although potentially biased). Thanks for sharing!
