### ISSUE TITLE
Check window transformations for time series

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#1047]
Seems like the windowed transformation is length `WINDOW+1` for `_previous_target` but it should be `WINDOW`-lengthed.

**Comment by paxcema** [comment]
Context from mindsdb#4083:

## Current Behavior

Number of values in __mdb_ts_previous_target column is 1 greater than WINDOW.
Number of values in order_by column is same as WINDOW.

## Expected Behavior

WINDOW number of values in __mdb_ts_previous_target

## Steps To Reproduce

https://docs.google.com/document/d/1CDNT_3yerSezVOgOESv49CnXYPD2vFwcrnNcSoMQYcY/edit?usp=sharing

**Comment by Ricram2** [comment]
Close if this is a false alarm.
