### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by djKooks** [mindsdb/lightwood#105]
**Describe the bug**
Setup python linter for project

**Expected behavior**
Linting code

I know this is not the main purpose of the project, but I think that setup linter will be better for project maintenance.

How do you think?

**Comment by George3d6** [comment]
Feel free to add a linter + run it through the code and make modifications where you spot errors, if the linter indeed spots relevant errors then we'll use said linter and we'll have corrected some errors while at it. If the linter doesn't find any "real" issues/errors then that means a linter is not needed.

**Comment by ZoranPandovski** [comment]
Flake8 will be the best option, I guess we will have a lot of pep8 warnings.

**Comment by George3d6** [comment]
I'm fine with whatever linter @djKooks  or anyone that takes this on sees fit. I don't really care about warnings related to an extra line between tow functions or something like that, not for now, when that will be required we can just get an extra formatter.

If any of the warnings impact the actual functionality of the code, that's what we need to focus on.

**Comment by djKooks** [comment]
@George3d6 @ZoranPandovski thanks for suggestions! I'll send PR when ready.

**Comment by djKooks** [comment]
@George3d6 
I've just update lint-fix PR in #107 . Please check.
It currently only includes auto-fix result, so I'll keep update. 

For checking lint status, I've also add setup for `flake8` following @ZoranPandovski 's suggestion.
Hope to discuss about detail lint rule, and settings if you have suggestion.

Thanks.

**Comment by George3d6** [comment]
@djKooks tests are ran automatically.

**Comment by George3d6** [comment]
Linter is setup (though I think we ought to run it manually more often)
