### ISSUE TITLE
Could not find a version that satisfies the requirement torch>=1.1.0.post2

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#11]
Installing lightwood produces the following error:

>  ERROR: Could not find a version that satisfies the requirement torch>=1.1.0.post2 (from lightwood) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0)
ERROR: No matching distribution found for torch>=1.1.0.post2 (from lightwood)

The strange thing is that torch 1.1.0.post2 version is available on [PyPi](https://pypi.org/project/torch/#history). Similar issues are reported on [pytorch repo](https://github.com/pytorch/pytorch/issues/10443)

**Comment by ZoranPandovski** [comment]
Fix provided on #14 PR

**Comment by George3d6** [comment]
There's still some issues with this when installing a docker container, #18 should fix it, but I'm leaving it open until I can confirm it works in more environemnts.

**Comment by UltraSpecialException** [comment]
@George3d6 I'm trying into install torch in a docker image and it's giving me the error shown in the OP's post. I'll quote it below as well:
>ERROR: Could not find a version that satisfies the requirement torch==1.1.0.post2 (from -r >requirements.txt (line 17)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, >1.0.1, 1.0.1.post2, 1.1.0)
>ERROR: No matching distribution found for torch==1.1.0.post2 (from -r requirements.txt (line 17))

Do you know if there's a get around?

**Comment by George3d6** [comment]
@UltraSpecialException  Does installing lightwood still fail if you install via `pip install git+https://github.com/mindsdb/lightwood.git@master` ?

If so, what python version are you using in said container ?

**Comment by UltraSpecialException** [comment]
@George3d6 I didn't try that. I installed torch on my local machine using `pip install torch` and I did `pip freeze > requirements.txt`, and the requirement in the .txt file becomes `torch==1.1.0.post2`. So I deleted that line in `requirements.txt` and just did a separate `RUN pip install torch` and it works so...

**Comment by George3d6** [comment]
Consider installing torch via the pip install command given above, it's sourced by lightwood from a different repo (other than pypi)

If you want to install troch standalone, go to: https://pytorch.org/

**Comment by ZoranPandovski** [comment]
I haven't experienced the same issue with the latest lightwood versions so I guess we should close this one @George3d6 .
