### ISSUE TITLE
Add main module to the sample code in the documentation

### ISSUE THREAD

**Issue by TalaatHasanin** [mindsdb/lightwood#1111]
This issue about improving the documentation by add main module for windows user.
I was running the code on a virtual environment using PyCharm and got a run time error because of spawning that required the code using main module.

`if __name__ == "__main__":
       main()`

@paxcema

**Comment by paxcema** [comment]
Hi @TalaatHasanin, can you please share the full error that you get?

The quick start code runs fine in my local macOS venv with PyCharm, so it's a bit surprising that it's failing on Windows.

**Comment by TalaatHasanin** [comment]
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

This is the error @paxcema

**Comment by paxcema** [comment]
Thanks @TalaatHasanin, that makes sense.

Are you interested in contributing a fix? If so, please go ahead and add an `if __name__ == '__main__':` clause for the sample doc and open a pull request.

**Comment by TalaatHasanin** [comment]
Yes I'm, Assign me please @paxcema
