### ISSUE TITLE
Support for Python >3.10

### ISSUE THREAD

**Issue by anushas-dev** [mindsdb/lightwood#1124]
Hi there!
I see for the dev environment setup python version should be in the range >=3.7, < 3.10.
Is there a plan to support higher versions of python anytime soon?

Thanks.

**Comment by ZoranPandovski** [comment]
Hey @anushas-dev, currently, we don't support 3.10  because many of our dependencies don't support it. Should be supported soon

**Comment by anushas-dev** [comment]
sounds good, thank you!
