### ISSUE TITLE
Reiter or refactor unused/old encoders

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#113]
The unused encoders are as follows:

1. NnAutoEncoder

2. RnnEncoder

3. InferSentEncoder

*** 

1. I think the idea of an auto-encoder for images is potentially good, but it should be significantly different, e.g. use conv layers, maybe use some pre-trained weights from a resnet. I also think it might take a long time to train compared to our current encoders.. In principle something like this architecture: https://github.com/phillipi/pix2pix might work.

2. This is broken at the moment, and we have enough text encoders in the form of BERT and InferSent, plus the plans to add more. I think we should remove it.

3. This is slower to train and poorer performing than BERT, not to mention it's very memory hungry, I think we should leave it in for now but remove it a few months down the line if we find no use for it.

**Comment by George3d6** [comment]
@paxcema @torrmal what do you think about this ?

There's even more unused encoders now, what should be our policy ? remove these ? mark as deprecated ? just lave them as is in case a user wants to work on them ?

**Comment by paxcema** [comment]
I think that if there is a working superior alternative (as in BERT vs InferSent), then it doesn't make too much sense to leave them around in the same folder. Maybe structure those cases in a `deprecated` folder, so that if anyone wants to take a look/test/extend them they still can.

**Comment by paxcema** [comment]
As discussed, we are removing the following encoders for the next release:

Text:
- Flair encoder
- InferSent encoder

Time Series:
- Cesium encoder
- TsFresh encoder

This will also solve #292.
