### ISSUE TITLE
Error: AttributeError: module 'lightwood' has no attribute 'data'

### ISSUE THREAD

**Issue by tauhidshah** [mindsdb/lightwood#1143]
I am new to the library and trying a simple multi-class classification problem. However, the line,

# Generate JSON-AI code to model the problem
json_ai = json_ai_from_problem(df, problem_definition=pdef)

    

is giving me the following error,

"INFO:lightwood-5070:Dropping features: []
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-e34b9d0590f2>](https://localhost:8080/#) in <cell line: 2>()
      1 # Generate JSON-AI code to model the problem
----> 2 json_ai = json_ai_from_problem(df, problem_definition=pdef)
      3 
      4 

[/usr/local/lib/python3.10/dist-packages/lightwood/api/high_level.py](https://localhost:8080/#) in json_ai_from_problem(df, problem_definition)
     53     df = df.drop(columns=problem_definition.ignore_features)
     54 
---> 55     type_information = lightwood.data.infer_types(df, problem_definition.pct_invalid)
     56     statistical_analysis = lightwood.data.statistical_analysis(
     57         df, type_information.dtypes, type_information.identifiers, problem_definition)"

**Comment by paxcema** [comment]
Hi @tauhidshah :wave: 

It seems you are running this inside a Jupyter notebook, right? Where is it stored? Issues like this one usually appear if you run python or jupyter from the repo's root folder.

**Comment by paxcema** [comment]
Were you able to solve this @tauhidshah?

**Comment by paxcema** [comment]
Closing as stale, feel free to reopen if you encounter this issue again.
