### ISSUE TITLE
Fix 'ambiguous variable name 'l' issue in lightwood\encoder\text\helpers\rnn_helpers.py

### ISSUE THREAD

**Issue by truesoni** [mindsdb/lightwood#1188]
Improvement Suggestion: 
Found an issue: ambiguous variable name &#39;l&#39;

It's currently on:
```
[lightwood\encoder\text\helpers\rnn_helpers.py:247]
```

Variables named I, O, and l can be very hard to read. This is because the letter I and the letter l are easily confused, and the letter O and the number 0 can be easily confused.
Change the names of these variables to something more descriptive.

Example of incorrect code:
The code in this example could be misinterpreted to be 0 * 1.08 (zero times one-point-eight).

```
O = 100.0
total = O * 1.08

```
Example of correct code:
This example clarifies that we're multiplying an order variable by another number.

```
order = 100.0
total = order * 1.08

````

**Comment by paxcema** [comment]
Hi @truesoni, thanks for highlighting this.

The file you indicate is actually deprecated, and cannot be used at all. If anything, we should actually remove this from the source code. Will open up an issue for that, but I'll close this one as won't fix.

**Comment by truesoni** [comment]
ok, thanks for the feedback
