### ISSUE TITLE
ImportError : cannot import name 'MinMaxScalar' from 'sklearn.preprocessing'

### ISSUE THREAD

**Issue by PRANESH-SELVARAJ** [mindsdb/lightwood#153]

**Comment by ZoranPandovski** [comment]
@PRANESH-SELVARAJ Can you please add more information about this issue? 
1. Steps to reproduce the behavior:
2. Describe the bug, lightwood version that you are using
3. Include stack trace

**Comment by George3d6** [comment]
It's a rather odd error, since we don't import `MinMaxScalar` directly... will close unless further information is provided unless you can provide at least an error log there's no way for us to debug this.
