### ISSUE TITLE
Predict with missing columns

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#165]
WIP as to how we can actually do this, tried a bunch of ways, they all failed in one way or another.

E.g. Dropout works well for categorical values but not for numerical values.

I'm awfully afraid this will end up being un-doable or a very complex edifice, but maybe there's a quick and easy way to do it, I'm holding on hope.

Either way, we need to take care of  #164 first.

**Comment by paxcema** [comment]
An update: as discussed with @torrmal, an interesting idea is to use a denoising autoencoder to impute missing columns at inference time. This [paper](https://arxiv.org/pdf/1705.02737.pdf) shows a possible implementation.

**Comment by George3d6** [comment]
Closing this for now, dropout impl solved this in part... dealing with the issue more broadly will be an objective of it's own.
