### ISSUE TITLE
Imporve lightwood documentation

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#167]
We need to make sure that the lightwood documentation will be up to date, and maybe enrich it a bit with some examples, for the v0.5.0 release.

@ZoranPandovski , I assume all of that has been moved to the separate docs repository, correct?

**Comment by ZoranPandovski** [comment]
Yes, https://docs.mindsdb.com/lightwood/info/. We can make the required changes in the docs repository.
