### ISSUE TITLE
pipeline is not define

### ISSUE THREAD

**Issue by ankybad** [mindsdb/lightwood#173]
NameError                                 Traceback (most recent call last)
<ipython-input-58-61d4a8a34fa0> in <module>
      1 from sklearn.pipeline import Pipeline
      2 from sklearn.preprocessing import StandardScaler
----> 3 my_pipeline= pipeline([
      4     ('imputer' , simpleimputer(strategy='medium')),
      5     ('std_scaler', standardscaler)

NameError: name 'pipeline' is not defined

**Comment by George3d6** [comment]
@ankybad , can you please provide the code that generated this error ?

**Comment by maximlopin** [comment]
`Pipeline` is imported with a capital P at line 1, being referenced as `pipeline` with lowercase p at line 3

**Comment by George3d6** [comment]
Fixed now.
