### ISSUE TITLE
Lightwood hangs when running from_data_ds.prepare_encoders for timeseries data

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#182]
**Describe the bug**
This mindsdb test takes forever to execute (literally):
https://github.com/mindsdb/mindsdb/blob/master/tests/unit_tests/libs/controllers/test_predictor.py#L225

Debugging it leads to this line of code executing forever:
https://github.com/mindsdb/lightwood/blob/master/lightwood/api/predictor.py#L213

**To Reproduce**
1. Use ide to set breakpoint on this line
2. Run tests with debugger on

**Comment by paxcema** [comment]
This was solved by #247, although the test is now failing for an unrelated reason.
