### ISSUE TITLE
Add sampling for training the encoders

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#184]
The `priming_data` used for training the encoders should be sampled if it's too large and we are training too many encoders.

**Comment by btseytlin** [comment]
@George3d6 is this the appropriate place to sample training data?
https://github.com/mindsdb/lightwood/blob/stable/lightwood/api/data_source.py#L275

Or should it be done in each Encoder instance?

**Comment by George3d6** [comment]
So... I'm not sure to be honest.
I think we could go either way, the advantage with sampling inside the encoder is:

* Some encoders take a long while to prepare and might not require all the data (e.g. Rich Text Encoders, Categorical AutoEncoders when the category is dense enough that it ends up training the autoencoder network, image encoders... when we get to actually training those, because we don't at the moment, because I found it annoying to impl and it's not a priority)

* Other encoders might take very little to prepare and might require the full datasets, or would at least yiled a better encoding and the sunk time for preparing with millions of values would only be 10-30 seconds (e.g. One Hot Encoder, Numericlal Encoder)

**Comment by btseytlin** [comment]
After some discussion with George we decided to put the issue on hold, as sampling might not be the best approach. It can lead to encoders learning a distorted distribution of data

**Comment by George3d6** [comment]
@btseytlin feel free to close issues when they are put on hold, otherwise we just get swamped, in this case I think we landed on a pretty definitive `No` so not much point in keeping it around.

Then again, maybe it's just my OCD making me want to have as few open issues as possible ?
