### ISSUE TITLE
Validate the current trasnformed cache and cache disabling methodology

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#185]
Currently there's a mechanism we use to disable the transformed representation cache and instead run each "encode" function when the datasource is accessed, I'm not sure if it's the most efficient way to implement it though... I'm also not convinced that our current cache implementation is golden, ideally we should validate those and see if there are potential improvements we could make.

**Comment by btseytlin** [comment]
The caches seem ok to me.

I have taken a look at the data source caches here:
https://github.com/mindsdb/lightwood/pull/189

Added some tests while figuring out how they work.

I also used cProfile like `python -m cProfile -o prof tests/ci_tests/ci_tests.py`. The longest execution times are datasource.__getitem__ calls so it makes sense to cache them.
![Screenshot from 2020-07-03 12-28-01](https://user-images.githubusercontent.com/2098322/86455042-bb7b8f80-bd28-11ea-8bd3-d160674a354f.png)

It seems like there is still room for improvement, for some reason the encoders are quite slow at encoding. Maybe we can speed it up if we use matrix operations in encoders. Currently I can see that the Numeric one encodes stuff in a loop, which is very slow.
