### ISSUE TITLE
Move tests to pytest, add them to CI

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#187]
We have a somewhat established test structure in mindsdb_native. Lightwood basically has ready unit tests, so it would be good to have CI running them. Also migrating the tests is a good way to polish the testing workflow further. 

I propose to do it the following way:
* Just like in mindsdb native, the directory structure of tests should mimic the directory structure of the project
* Absolutely include `pytest-randomly` for fixing random seed and other utils from mindsdb_native `conftest.py` and `plugin.py`.
*

**Comment by George3d6** [comment]
For now, we are moving these to unittest until our A/B experiment is done.
