### ISSUE TITLE
WARNING:root:Failed to train helper mixers with error: 0

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#190]
Weird warning, occurs when running ci_tests.py

**Comment by George3d6** [comment]
Weird indeed, @btseytlin or @maximlopin  (however has time) can you look into it.

The helper mixer is an alternative gradient boosting mixer we use in certain scenarios, training them shouldn't fail, not with categorical/numerical targets at any rate.

Probably a silly issue, but could be a good intro to the helper mixers (though it's a concept we might replace) and to the overall logic in `predictor.py`. If you guys don't have time or can't find a reason ping me and I can look into it.

**Comment by maximlopin** [comment]
the traceback
```
Traceback (most recent call last):
  File "lightwood\api\predictor.py", line 274, in learn
    self._helper_mixers = self.train_helper_mixers(from_data_ds, test_data_ds, self._mixer.quantiles[self._mixer.quantiles_pair[0]+1:self._mixer.quantiles_pair[1]+1])
  File "lightwood\api\predictor.py", line 111, in train_helper_mixers
    boost_mixer.fit(train_ds=train_ds)
  File "lightwood\mixers\boost\boost.py", line 43, in fit
    sample_weight.append(weight_map[val])
KeyError: 0
```

**Comment by George3d6** [comment]
no longer relevant.
