### ISSUE TITLE
Bag of words text encdoer

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#194]
Add a bag of word text encoder that support `decode` in order to use as an output decoder for generating text tags based on some piece of text (e.g. think sentiment extraction with variable number of sentiments to be extracted)

The first step here would be finding a dataset that fits the issue @ZoranPandovski @torrmal know of any good candidates ?

**Comment by btseytlin** [comment]
Here's a good dataset:
http://www.cs.cmu.edu/~ark/personas/

Predicting movie genres from plot summaries

**Comment by btseytlin** [comment]
Another one:
https://www.kaggle.com/cryptexcode/mpst-movie-plot-synopses-with-tags

**Comment by btseytlin** [comment]
https://www.kaggle.com/stackoverflow/stacklite

**Comment by btseytlin** [comment]
Seems like BERT does well on multi-label text classification:
https://paperswithcode.com/sota/multi-label-text-classification-on-eur-lex

I think we should be fine with using Multilingual Distilbert (DistilmBERT):
https://github.com/huggingface/transformers/tree/master/examples/distillation

**Comment by btseytlin** [comment]
https://towardsdatascience.com/text-classification-with-state-of-the-art-nlp-library-flair-b541d7add21f

**Comment by George3d6** [comment]
added in the form of the multiple categories encoder.
