### ISSUE TITLE
Flair text encoder

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#196]
Flair should provide some (language and potentially even text-size) specific text encoders that generate an embedding (probably using a BERT model from huggingface much like we do).

We should consider using these out of the box the best way we can, could cut on a lot of time when encoding rich text since we wouldn't have to train the BERT encoder anymore (granted, we can do that even now, but Flair might have some better no-training-required model than the default huggingface weight, maybe not though ?)

**Comment by btseytlin** [comment]
It seems that flair is just an interface to transformers. It can save us from some boilerplate code, but from what I understand model-wise there is no benefit

**Comment by George3d6** [comment]
implemented. From benchmarking I agree with @btseytlin no real difference from just using hugging face directly except for boilerplate removal.
