### ISSUE TITLE
Predicting requires output columns to be provided

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#211]
The last line of this fails:
```
df = pd.read_csv("../../../datasets/mpst/mpst_full_data.csv")

df = df[['title', 'plot_synopsis', 'tags', 'split']]
df.tags = df.tags.apply(lambda x: x.split(', '))

df_train = df[df.split == 'train'].copy()
df_test = df[df.split == 'test'].copy()
df_train = df_train.drop(['split'], axis=1)
df_test = df_test.drop(['split'], axis=1)

config = {'input_features': [
        {'name': 'plot_synopsis',
         'type': 'text',
         },
    ],
    'output_features': [
        {'name': 'tags', 'type': 'multiple_categorical', 'encoder_class': MultiHotEncoder}
    ],
}
predictor = Predictor(config)

predictor.learn(from_data=df_train)
predictions = predictor.predict(when_data=df_test.drop(['tags'], axis=1))
```
The dataset is not relevant, but it's https://www.kaggle.com/cryptexcode/mpst-movie-plot-synopses-with-tags.
`DataSource.__getitem__` will attempt to encode the removed column `tags` and fail as the column is missing.

This works:
```
predictions = predictor.predict(when_data=df_test))
```
But in reality, the test targets are not available.

Currently mindsdb native handles this by passing a column of `None` instead of targets. This is a solution for as long as our encoders handle such columns.

The real solution is to not try to encode columns that are missing.

**Comment by George3d6** [comment]
Ouch, I didn't see this issue but yeah, this is a waste of compute and a very bad design flaw, let's move onto addressing this, @btseytlin or @maximlopin however of you is free first consider taking this one. We sould ignore the `output_columns` bit altogether for predicting. If this can be done without adding complexity to the Datasource that would be an ideal scenario but I'm not 100% sure it can be done.

**Comment by maximlopin** [comment]
working on it

**Comment by George3d6** [comment]
Should be part of next month's objectives.

**Comment by ilia-tsyplenkov** [comment]
The code provided in descripiton works fine, no any errors. @btseytlin @paxcema, is it still actual? I've done some review of  `Predictor and DataSource` code, but didn't discover any suspected. WDYT?

**Comment by ilia-tsyplenkov** [comment]
`ci_tests.py` doesn't exist anymore, right now all enabled tests are successful, no matter launched they in CI of locally

**Comment by ilia-tsyplenkov** [comment]
closed according to @btseytlin resolution
