### ISSUE TITLE
Stop once accuracy hits 100%

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#214]
There's situations where the test accuracy hits 100% and the loss is very minor, when this happens it should stop, otherwise the mixer enters this very weird overfitting loop trying to minimize a 0.0000x loss to a 0.000000x loss.

We can do this either by looking at the accuracy or but just looking at the loss and stopping when it's bellow a very tiny number (take `0.0005` as an arbitrary value, for example)

**Comment by btseytlin** [comment]
We can also stop when loss hits a plateau, for example if there is no improvement that's bigger than X for 5 epochs

**Comment by George3d6** [comment]
Already being done for the current NN mixer.
