### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#22]
I've tried to test lightwood with [home rentals
 example](https://github.com/mindsdb/lightwood/blob/master/docs/examples/home_rentals.py) but got ModuleNotFoundError: No module named '_lzma'.

Screenshot:
![Screenshot from 2019-07-24 18-44-02](https://user-images.githubusercontent.com/7192539/61812426-c6088600-ae43-11e9-995f-2c92ea82e430.png)

It looks like _lzma is a dependency to pandas, but it should be included with Python 3.x version.

**Comment by George3d6** [comment]
Weird that this would happen. Did you update/downgrade the pandas version after installing lightwood ?

**Comment by ZoranPandovski** [comment]
No, just plain install of lightwood

**Comment by George3d6** [comment]
hmh, weird, can't really replicate,  we should consider adding lzma as a dependency I guess.

What's the OS and python version for this ?

**Comment by ZoranPandovski** [comment]
Python version 3.7, Ubuntu 18.04, lightwood 0.7.6. I've upgraded to the latest 0.7.9 but the same issue

**Comment by ZoranPandovski** [comment]
With pandas 0.24 this works. But with version 0.25 that is a dependency in lightwood, it doesn't. Ok, so here is the explanation why [pandas issue](https://github.com/pandas-dev/pandas/issues/27543#issuecomment-514305279)
