### ISSUE TITLE
NumericEncoder error when attempting to encode missing (target) column in ci_tests

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#231]
Running `ci_tests.py` spams this error:
> ERROR:root:Can't encode target value: None, exception: '<' not supported between instances of 'NoneType' and 'int'

This is caused by the numerical encoder trying to encode the column `rental_price` when predicting. The column is missing from the data source because it's the output and not provided at prediction time.
Seems to be related to this: https://github.com/mindsdb/lightwood/issues/211

**Comment by George3d6** [comment]
Should be part of next month's objectives.

**Comment by ilia-tsyplenkov** [comment]
`ci_tests.py` doesn't exist anymore, right now all enabled tests are successful, no matter launched they in CI of locally (no any ERROR messages)
