### ISSUE TITLE
Challenge, TS encoders

### ISSUE THREAD

**Issue by torrmal** [mindsdb/lightwood#239]
`Warning: This issue is intended as a test to be given to candidates for a job at Mindsdb, please do not start working on it, unless we've message you telling you to do so.`

## Current state

We presently have an RNN-based encoder for timeseries data, which will take a sequence of arbitrary length, e.g. `[1, 2, 3, 4, 5, 6, .... , 2000]` and turn it into an embedding of a fixed size.'

It can be found here:

https://github.com/mindsdb/lightwood/blob/stable/lightwood/encoders/time_series/rnn.py

The unit tests for it can be found here:

https://github.com/mindsdb/lightwood/blob/stable/tests/unit_tests/encoders/time_series/test_rnn.py

They can be executed by cloning lightwood, installing the requirements (`pip3 install -r requirements.txt`), adding lightwood to your python path (e.g. `export PYTHONPATH=$PYTHONPATH:/home/<your user>/lightwood`) and then cd-ing into the cloned directory and running `tests/unit_tests/encoders/time_series/test_rnn.py`.

## The task

You need to create ONE of two new proposed time-series encoders:

- *Transformer encoder for TS*: The issue with RNNs is that they are sequential and therefore you can only parallelize on batches with padding. Transformers solve this, therefore the task at hand is to build a time series encoder based the transformer architecture. Please find inspiration here: https://towardsdatascience.com/how-to-code-the-transformer-in-pytorch-24db27c8f9ec

- *CNN encoder for TS*:  Implement a way to encode time-series data using CNNs, we invite you to use Restnet as the encoder (see inspiration here: https://github.com/hsinyilin19/ResNetVAE). *Bonus points if you use, Residual Attention.*

## Notes

* The specific unit tests to be written are left as an exercise for the implementer, the scope of the unit tests should be to assess performance as well as to see if the autoencoder is doing roughly what would be expected of it. You needn't validate anything about how the resulting embeddings behave when feeding further down the line into the mixer.

* Please ask any questions you might have here, unless they need to be private, since that way they can remain here as an FAQ

* Message us when you are done with this project, don't make a PR (since it would be visible to other participants that might not have finished yet)

* Ideally your encoder should run on both GPU and CPU, but if you only had time to make it work on one of them, tell us which

* Feel free to rewrite as much of the existing code as you wish, as long as the underlying functionality stays the same whatever changes you make should be fine.

**Comment by walexand3r** [comment]
Hi, I have a question: 
When encoding with a CNN, what shape / size are you expecting the encoded representation to be? Should it be a vector so rough comparisons can be made with the RNN, or is a 2D/3D latent space acceptable?

**Comment by ZoranPandovski** [comment]
This is already implemented, closing for now.

**Comment by walexand3r** [comment]
Sorry I should have clarified, there were two options in #239, this implements the other one. Patricio invited me to PR anyway.

**Comment by paxcema** [comment]
Yup, that's correct. Thanks for the PR @walexand3r! I'll get to reviewing it ASAP.
