### ISSUE TITLE
Windows Installation issue

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#26]
**Describe the bug**
Installation failed for lightwood=0.7.6. Error:

> Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.                               lightwood depends on torch@ https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl

**To Reproduce**
1. pip install lightwood=0.7.6 or just pip install lightwood since 0.7.6 is latest

**Desktop (please complete the following information):**
 - OS: windows 10
 - Lightwood version  0.7.6
 - Python Version 3.7.3

**Comment by George3d6** [comment]
I see... This is certainly a catch22 issue. Since the pypi torch version seems not to work for Windows and pypi won't let me install a custom wheel.

**Comment by George3d6** [comment]
This issue is "fixed" in that we now recommend installing lightwood through github rather than pip in the docs and do so in mindsdb's setup.

However, the fact that lightwood can't be installed via pypi still remains, moving to #28
