### ISSUE TITLE
Extract delta feature in timeseries encoder

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#264]
For certain timeseries column the RNN encoder (and other timeseries encoders) should contain a transformation that extracts the difference between every row and the previous row.

For example, given column: [123,124,126] the delta extracted would be [1,2].

Whether or not we actually need this or the encoder should be able to infer this from the data is arguable, @paxcema mentioned it's a feature @torrmal wished to include so I'm creating the issue here, feel free to further discuss as to whether or not this is relevant.

**Comment by George3d6** [comment]
@paxcema is this still something we plan on doing at some point ? If not, consider closing the issue.

**Comment by paxcema** [comment]
Most likely no, I think the sinusoidal components are describing the delta just fine. Closing for now.
