### ISSUE TITLE
The decoder is not sent to the new device in the `to()` function

### ISSUE THREAD

**Issue by Lezcano** [mindsdb/lightwood#282]
In the `to()` method within the class `RnnEncoder`
https://github.com/mindsdb/lightwood/blob/stable/lightwood/encoders/time_series/rnn.py#L36
the decoder is not sent to the new device. This would give a runtime error when this function is used in practice.

More generally, this design of reimplementing the `to()` method seems dubious. In the case that one wants to go this way, it would be necessary to implement also all the other recursive methods that `nn.Module` such as `.float()`, `.half()` and so on.

Unless there is a strong reason for not doing so, I would recommend to make `BaseEncoder` inherit from `nn.Module`. If this is not possible---which I guess it is the case, as otherwise you would have already done this---I would recommend to reimplement these functions at `BaseEncoder` via some metaprogramming, to avoid bugs like this one.

**Comment by George3d6** [comment]
> Unless there is a strong reason for not doing so, I would recommend to make BaseEncoder inherit from nn.Module. If this is not possible---which I guess it is the case, as otherwise you would have already done this

@Lezcano this is indeed not possible, or at least not desirable, since certain (loads of?) encoders are not neural networks and/or not pytroch nn.Modules specifically (e.g. see BERT encoders, OHE and numeric/dates encoders)

**Comment by George3d6** [comment]
> I would recommend to reimplement these functions at BaseEncoder via some metaprogramming, to avoid bugs like this one.

Could you be a bit more specific here ?

The way I see it every encoder's `to` method might be different, in that the way we use `to` is just to optimize/switch encoders to GPU or to CPU (or to a specific GPU out of a bunch). I'm not sure how we could make sure this function is implemented correctly via metaprogramming, testing seems like the only way to check, but I'm all ears since your solution might be useful for other things as well.

**Comment by Lezcano** [comment]
A basic implementation would go along this lines:
```python
def to(self, device):
    for v in vars(self):
        attr = getattr(self, v)
        if isinstance(attr, nn.Module):
            attr.to(device)
```
Of course this could be extended to consider also `torch.Tensor` and moving them. This `to()` method can be more generally used to change the type of the tensors in the model, so methods like `half()`, `float()` and so can be implemented in terms of this one.

**Comment by George3d6** [comment]
@paxcema , thoughts ? In principle implementing something like the above in the base encoder seems fairly clever, especially since we have multiple nn-based encoder we need to swithc between GPU and CPU
