### ISSUE TITLE
Issue with somewhat common naming schema

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#306]
Replace:

Train a native Predictor with `https://raw.githubusercontent.com/mindsdb/benchmarks/main/datasets/dow_jones/data.csv` and lightwood will throw an error.

Why ? `previous_x` and `x` can be columns that come together in a file, it's rather common in hindsight. However we use the column name `previous_{target_col_name}` and such in a bunch of places for timeseries problems.

We need to change `previous_` to something like `__mdb_ts_previous_`

**Comment by paxcema** [comment]
Implemented in #313, closing.
