### ISSUE TITLE
Question: How to load model from S3

### ISSUE THREAD

**Issue by qmegas** [mindsdb/lightwood#364]
Hi,

Is it possible to load pretrained MindsDB model from S3? Something like that?
```python
import lightwood

predictor = lightwood.Predictor(load_from_path='s3://my-bucket/models/somemodel/v1/icp.pickle')
```

**Comment by paxcema** [comment]
Hello @qmegas,

The recommendation here is to use [MindsDB](https://github.com/mindsdb/mindsdb/) facilities to train, save and load models (using Lightwood under the hood). You can find more information on how to do this [here](https://docs.mindsdb.com/FunctionalInterface/). Let me know how it goes!
