### ISSUE TITLE
Transfering components to ONNX

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#368]
An ML focused IR used by pytorch: https://onnx.ai/

Can we transfer (lightwood) Predictor to it ? Or at least the mixer + all the encoders

Before or after training ?

Does it bring any advantages? How hard it it ?

**Comment by paxcema** [comment]
The benefit I see is improved inference time once the model has been trained and exported to ONNX format. This would mean some sort of "high-performance" mode where we would run the trained model in the ONNX runtime.

Disadvantages: 
- seems like PyTorch [cannot](https://github.com/pytorch/pytorch/issues/21683) load ONNX models once exported.
- only can export [torch](https://pytorch.org/docs/stable/onnx.html) models and [lightgbm](https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/lightgbm/operator_converters/LightGbm.py) models, which means we need to save the encoders and mixer of the predictor as separate files.

**Comment by George3d6** [comment]
Closing for now, the demand for this didn't really grow into anything ,and as mentioned by @paxcema 's comment it's too complicate to transfer lightwood models.
