### ISSUE TITLE
No module named 'lightwood.constants'

### ISSUE THREAD

**Issue by Duoquote** [mindsdb/lightwood#372]
Here is the code,
```python
from lightwood import Predictor
```

Here is the output:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-0e5a48023d5e> in <module>
----> 1 from lightwood import Predictor

E:\Projects\nextgeo\analysis\py_analysis\lightwood\__init__.py in <module>
----> 1 from lightwood.constants import lightwood
      2 name = "lightwood"

ModuleNotFoundError: No module named 'lightwood.constants'
```

My local anaconda installation is kind of broken so it maybe because of mine. What should I do? I can also give more details if you tell me the commands. Thanks!

**Comment by paxcema** [comment]
Hi @Duoquote,

What directory is the iPython notebook saved at? This import error can happen if the notebook is in the same folder than lightwood is. For example:

```
.
├── notebook.ipynb
├── lightwood
│   ├── docs
│   ├── __init__.py
│   ├── install.sh
│   ├── LICENSE
│   ├── lightwood
│   ├── README.md
│   ├── requirements.txt
│   ├── tests
│   ├── ...
```
would fail. Try moving the notebook to a different folder and let me know if it works.

**Comment by Duoquote** [comment]
That makes sense... I installed the module from github repo with setup.py and I left it there, my apologies!
