### ISSUE TITLE
Implement truncated BPTT in RNN time series encoder

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#384]
Currently, passing too big a window in a time series task will run the GPU out of memory when using the RNN time series encoder. This is solved, as shown in the transformer encoder pull request (#285), by truncating the BPTT procedure.

**Comment by George3d6** [comment]
just relabling since this is not a bug, just a nice-to-have feature that allows slightly slowing down training in order to handle with large samples.

**Comment by paxcema** [comment]
Will close, as it is expected behavior and we do not want to forcefully cap the window/history for users who do have the computational resources.
