### ISSUE TITLE
Merge with mindsdb native

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#388]
Long overdue. For now we can:
* Move lightwood into the "backend" directory of mindsdb_native and keep namespace separation (I think this should be doable via smart usage of __init__.py files)
* Remove type detection from lightwood
* Unify tests
* Rename lightwood `Predictor` to `Model` and remove the save/load functionality.
* ... rough outline, we could start differently, more things to come, ideas welcome
* Remove "state" from this new project, predictors will still be save-able and load-able, but this project will not handle storing them on the file-system. 

People who will hopefully help with this include myself, @paxcema , @maximlopin @torrmal 

Will probably start mid-Feburary but to be decided.

Design doc: https://www.notion.so/mindsdb/Native-Lightwood-merger-5d41d30b78bb455892dbb6ab8ef91e15 (moving towards this will be a gradual process)

**Comment by flozi00** [comment]
Hi
Whats the state of this task?
Already worked with ludwig (you tell it inspired you) and tensorflow before, but in last time pytorch took more and more the prior framework.
So I am interested in adding especially NLP models to this library. Should I wait until refactoring ?

**Comment by paxcema** [comment]
Hi @flozi00,

This is being targeted for end of this month, but no guarantees it won't get delayed further.

I would say if you are interested in adding NLP models, you can go ahead and do so. The encoder-mixer approach is not changing in the merge, so your efforts wouldn't be wasted.

For reference, [here's](https://github.com/mindsdb/lightwood/blob/stable/lightwood/encoders/text/pretrained.py) our NLP encoders. Don't hesitate to reach out if you have further questions.

**Comment by George3d6** [comment]
New update is that we might start on this mid-may depending on the state of various other things we're working on. Also might be worth making our documents for this public here @torrmal @paxcema @hakunanatasha , thoughts on this?

**Comment by paxcema** [comment]
Update: the refactor is well underway. @George3d6 has managed to get flows working end to end for simple data types. Hopefully, we'll be able to release this in the next month or two.

**Comment by George3d6** [comment]
Closing since the data here doesn't well align with what in-practice is contained within the refactor
