### ISSUE TITLE
Input parameters error for callback_on_iter()  function

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#39]
**Describe the bug**
TypeError is thrown when training a new model. 
In the latest version of lightwood, accuracy is sent to callbeck_on_iter function that doesn't accept that parameter https://github.com/mindsdb/lightwood/blob/245d5f66c75a0e70f5e345b2e1b4da18b93cdd71/lightwood/api/predictor.py#L292

**To Reproduce**
1. Train new data
2. See error:  callback_on_iter() takes 5 positional arguments but 6 were given

**Screenshots**
![Screenshot from 2019-09-05 01-07-42](https://user-images.githubusercontent.com/7192539/64999193-1a316300-d8e7-11e9-903c-e84ea289638b.png)

**Comment by George3d6** [comment]
Resolved in: https://github.com/mindsdb/mindsdb/pull/303
