### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#41]
**Describe the bug**
`TypeError: object of type 'NoneType' has no len()` is thrown when using lightwood as backend.

**To Reproduce**
1. Use [this example](https://github.com/ZoranPandovski/mindsdb-examples/tree/master/fifa18_players)

**Screenshots**
![Screenshot from 2019-09-02 17-31-02](https://user-images.githubusercontent.com/7192539/65591177-49ea0600-df8c-11e9-99f2-ba3909c8e859.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Lightwood version 0.9.0
 - Python Version 3.7.4

**Comment by George3d6** [comment]
Odd that it would throw that error... also odd that it would use the RNN encoder for the columns in there, none of them look like rich text to me. I'll look into both issues, cheers.
