### ISSUE TITLE
MindsDB doesn't train for torch 1.7 but will work for 1.8.1

### ISSUE THREAD

**Issue by hakunanatasha** [mindsdb/lightwood#418]
* Python version: 3.8.5
* Operating system: Ubuntu 20.04 (also Mac OSX)
* Additional info if applicable:

Installing mindsdb with default requirements seems to fail training. However, training the model with updated torch=1.8.1 seems to work just fine.

**Comment by paxcema** [comment]
@hakunanatasha the 0.64.1 hotfix should address this issue, can you confirm this is the case?

**Comment by hakunanatasha** [comment]
I just made a testing environment with 1.7 and the bare minimum required packages; works just fine- thanks for the catch!
