### ISSUE TITLE
can't pickle predictor

### ISSUE THREAD

**Issue by maximlopin** [mindsdb/lightwood#446]
got this error when calling `.save()` on an instance of `PredictorInterface`
```
  File "Q:\Desktop\mdb\mindsdb\mindsdb\interfaces\model\model_controller.py", line 443, in fit_predictor
    lw_p.save(os.path.join(config['paths']['predictors'], name))
  File "Q:\Desktop\mdb\lightwood\lightwood\api\predictor.py", line 18, in save
    pickle.dump(self, fp)
_pickle.PicklingError: Can't pickle <class 'a_temp_module.Predictor'>: import of module 'a_temp_module' failed
```

to reproduce, generate a predictor then train it via the http api in mindsdb (https://github.com/mindsdb/mindsdb/pull/1307)

**Comment by George3d6** [comment]
Ok, this is... surprising. Not sure how easy the fix will be, I will try to fix this today.

**Comment by George3d6** [comment]
this was fixed, forgot to close
