### ISSUE TITLE
Wrong inferred type for datetime

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#468]
Lightwood version: staging

## Describe your issue
As reported by @Ricram2, a datetime column with format `%Y-%m-%d %H:%M:%S` can be mistyped as quantity and then fails to parse:

![image](https://user-images.githubusercontent.com/12536303/130646839-de3cf3e7-126f-42bf-9585-a6d61e8dfe14.png)

**Comment by George3d6** [comment]
I believe this was fixed, it happened in the snowflake dataset for which we have deployed a fix a while ago.
