### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#470]
## Your Environment
* Operating system: macOS in an M1 apple computer

## Describe your issue
As reported by @alejandrovillegas, installation currently fails in MacBooks with M1 processors. See attached log for more details.
[m1_issue.txt](https://github.com/mindsdb/lightwood/files/7042557/m1_issue.txt)

**Comment by George3d6** [comment]
If you stumble upon this issue and need support, please shout, right now I'm not sure how many users run into this and how much we should care

**Comment by George3d6** [comment]
Potentially useful resources to get this running:
1. https://www.hendrik-erz.de/post/setting-up-python-numpy-and-pytorch-natively-on-apple-m1
2. https://www.mostlyphysics.net/blog/2021/2/6/scientific-computing-on-an-apple-m1-system

We have to remember to post an update once @alejandrovillegas figures out how to run on his machine

**Comment by George3d6** [comment]
Update: Loads of libraries still failing, I don't expect this to work until at least 6-18 months in.

**Comment by paxcema** [comment]
Update: as detailed in #953, it is now possible to manually get a working installation if using `miniconda` and `conda-forge`.
