### ISSUE TITLE
Convert trained models to Onnx

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#477]
After #473 is done

Try converting the already trained model to the onyx IR and see if that improves performance (if it does think about how this can be integrated with normal loading and saving, ideally keep both this IR and the source if certain env are incompatible with running onyx)

**Comment by paxcema** [comment]
For this, we need a flag that will constrain AutoML design space to PyTorch encoders and mixers only.

**Comment by paxcema** [comment]
Closing for now.
