### ISSUE TITLE
One-hot encoder mode to work without unknown categories

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#492]
## Task

Categorical data is fully supported by lightwood. One of the available encoders for this data type is the [one-hot encoder](https://github.com/mindsdb/lightwood/blob/staging/lightwood/encoder/categorical/onehot.py).

The one-hot encoder (OHE) currently always outputs a vector with size `n_categories+1`, where the extra index is reserved for `unknown` or `missing` categories.

This task consists in adding a mode to the OHE (i.e. a boolean flag in the constructor) so that it doesn't create an index for `None/Unknown`, so that it is forced to always predict a previously seen category.

## Steps :male_detective: :female_detective: 

- Fork the Lightwood repository, checkout the `staging` branch and from it create a new one.
- Implement the change. Please, feel free to ask questions in the comments below.
- Make the PR and address any comments that reviewers might make.

## Additional rewards :1st_place_medal: 

Each encoder PR brings 5️⃣  points for entry into the draw for a :computer:  Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag :shirt: :bear: .  For more info check out https://mindsdb.com/hacktoberfest/

**Comment by mrandri19** [comment]
What should the behaviour be in this?
Return a vector full of zeros, or crash like in scikit-learn's one hot encoder?
