### ISSUE TITLE
Cuda-enabled Learning

### ISSUE THREAD

**Issue by danpechi** [mindsdb/lightwood#51]
Hi,

How do I modify the learn method to be cudified? I saw some stuff from earlier with specifying devices, etc, but wasn't sure about the details there as I couldn't find anything in the documentation

**Comment by George3d6** [comment]
Here's an example for how to enable cuda (gpu usage via pytroche's cudnn interface, that is):

```
import lightwood

lightwood.config.config.CONFIG.USE_CUDA = True

#... rest of your code
```

If you don't specify this argument it will be auto-set to `True` if we can detect a GPU on your machine via `torch.cuda.device_count()`

If you want to specify a given cuda device use:

`lightwood.config.config.CONFIG.USE_DEVICE = '{device_name}`

These configuration options work like switches so you can toggle them on and off during the time you run lightwood code and all models will train and/or predict on the gpu/cpu or the specified device accordingly. So a GPU trained model and predict on the CPU and vice versa.

Hopefully this solves your issue, unless I'm miss-understanding what you mean by `cudified`.
We should probably document this stuff better but, there's only so much time available at the moment and this has not been a top priority, as there are few lightwood users compared to mindsdb users.

**Comment by George3d6** [comment]
Ok, no answer for 1 month, so I will close this for now. Feel free to leave a comment if the above answer did not fix this for you and I will re-open it (or open another issue).
