### ISSUE TITLE
`sktime` missing dependency

### ISSUE THREAD

**Issue by VladPerervenko** [mindsdb/lightwood#510]
In requirements.txt
`sktime[arima] >= 0.5.0`
bat 
`(mindsdb) C:\Users\User>pip install sktime[arima]>=0.5.0
WARNING: sktime 0.7.0 does not provide the extra 'arima'`
install
`(mindsdb) C:\Users\User>pip install sktime[arima]==0.5.0`

**Comment by ZoranPandovski** [comment]
Hi @VladPerervenko thanks for reporting this. We will check if we still need to install sktime with `arima`. Did this stop the lightwood installation, I guess you can count it as working for now.

**Comment by paxcema** [comment]
As an update @VladPerervenko, the fix for this will be included in this week's Lightwood release.
