### ISSUE TITLE
import Predictor

### ISSUE THREAD

**Issue by VladPerervenko** [mindsdb/lightwood#511]
`(mindsdb) C:\Users\User>python
Python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from lightwood import Predictor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Predictor' from 'lightwood' (C:\Users\User\AppData\Local\R-MINI~1\envs\mindsdb\lib\site-packages\lightwood\__init__.py)`

What's wrong?
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

**Comment by George3d6** [comment]
Hi, the lightwood documentation is outdated, please install `lightwood<1.0.0` if you wish to use the old version *or* wait 2 or 3 more weeks for us to get the documentation out for the new one.

If you really want to use the new one now check out `tests/integration/base` for some examples, but you'll have to learn it w/o the training wheels so to speak. If you're not in a hurry though I suggest you just check back this repo on the 1st of October.

**Comment by paxcema** [comment]
I can also offer this fairly minimal example:

```python
import pandas as pd
from lightwood.api.high_level import ProblemDefinition, predictor_from_code, json_ai_from_problem, code_from_json_ai


if __name__ == '__main__':
    # Load and split data
    df = pd.read_csv("https://s3.eu-west-2.amazonaws.com/mindsdb-example-data/home_rentals.csv")
    train_df = df.sample(frac=0.8)
    test_df = df[~df.index.isin(train_df.index)]
    
    # Define predictive task
    target = 'rental_price'
    pdef = ProblemDefinition.from_dict({'target': target,  # column to predict
                                        'time_aim': 30,    # time budget to build a predictor
                                        })
    # Generate predictor code
    json_ai = json_ai_from_problem(train_df, problem_definition=pdef)
    predictor_class_code = code_from_json_ai(json_ai)

    # Train predictor
    predictor = predictor_from_code(predictor_class_code)
    predictor.learn(train_df)

    # Predict for test data
    test_preds = predictor.predict(test_df)

    # Save predictor and its code
    pred_name = 'home_rentals_predictor'
    predictor.save(f'./{pred_name}.pkl')
    with open(f'./{pred_name}.py', 'wb') as fp:
        fp.write(predictor_class_code.encode('utf-8'))  # save predictor code
```
