### ISSUE TITLE
Lightwood.api.ensemble is not necessary

### ISSUE THREAD

**Issue by hakunanatasha** [mindsdb/lightwood#517]
This script is deprecated, as the ensemble module has moved to `lw.ensemble` with a base abstraction. A quick inspection of the code (ex: grep for this call) and I don't see any references. Please double check if this file is required, as I think it should be removed.

The culprit link is [here](https://github.com/mindsdb/lightwood/blob/0372d292796a6d1f91ac9df9b8658ad2f128b7c9/lightwood/api/ensemble.py)

**Comment by paxcema** [comment]
Double checked, it's from pre-lightwood 1.0.0, it should be removed (see #518).
