### ISSUE TITLE
accuracy_functions

### ISSUE THREAD

**Issue by hakunanatasha** [mindsdb/lightwood#522]
Currently the expectation of accuracy functions is a list of strings (see [here](https://github.com/mindsdb/lightwood/blob/0372d292796a6d1f91ac9df9b8658ad2f128b7c9/lightwood/api/types.py#L223)). This is a bit awkward because for custom performance metrics, an import and performance measure is required. We need to think of a more robust solution for this

Also, for the sake of clarity, I would vote we change this to 'performance_functions' but this is a very minor aside.

**Comment by paxcema** [comment]
Will leave this as-is _for now_.
