### ISSUE TITLE
Rename df_std_dev to df_target_stddev

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#555]
## Introduction

Lightwood is an AutoML library that aims at abstracting common procedures in the Machine Learning workflow (e.g. data preparation, feature engineering, model building, model analysis) with an approach that can be fully automated but easily customizable and extended thanks to its flexibility.

## Task

In this task, we seek to rename the `df_stf_dev` key where we store the target standard deviation statistic, to the more descriptive name `df_target_stddev`.

## Steps 🕵️‍♂️ 🕵️‍♀️

* Fork the Lightwood repository, checkout the staging branch and from it create a new one.
* Make the requested changes.
* Please report any issues that you find while working on this.

Make the PR and address any comments that reviewers might make.

## Additional rewards 🥇

The accepted PR for this issue brings :one: point for entry into the draw for a 💻 Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag 👕 🐻 . For more info check out https://mindsdb.com/hacktoberfest/

**Comment by George3d6** [comment]
Resolved in: https://github.com/mindsdb/lightwood/pull/714/
