### ISSUE TITLE
Implement an audio encoder

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#614]
## Task

Lightwood handles many different data types, and we're always looking to include more.

One possible data type to experiment with is an [audio encoder](https://github.com/mindsdb/lightwood/blob/staging/lightwood/encoder/audio/amplitude_ts.py); if you are interested in tackling this, _please_ ping the research team (either me, @hakunanatasha or @George3d6) in the discussion here, to propose your initial approach and scope your contribution together ✨. 

Ensure you implement a unit test plus any modifications needed to obtain an encoded representation from audio in order for this PR to be accepted.

## Steps :male_detective: :female_detective: 

- Fork the Lightwood repository, checkout the `staging` branch and from it create a new one.
- Implement a unit test that generates an instance of your encoder, some (potentially synthetic) audio data, and proceed to encode-decode it. [This](https://github.com/mindsdb/lightwood/blob/f469fd49f1859bd0444094fd378c9508e99871cf/tests/unit_tests/encoder/time_series/test_timeseries_rnn.py#L22) unit test can be useful as a reference, and the (outdated) [`AmplitudeTs` encoder](https://github.com/mindsdb/lightwood/blob/staging/lightwood/encoder/audio/amplitude_ts.py) as inspiration or starting point for your own encoder (in fact, feel free to replace it).
- Accuracy of the encoder is to be discussed with our team, so don't get discouraged if encoded representations are not perfect; this is a hard problem!
- Make the PR and address any comments that reviewers might make.

## Additional rewards :1st_place_medal: 

Each encoder PR brings 5️⃣  points for entry into the draw for a :computer:  Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag :shirt: :bear: .  For more info check out https://mindsdb.com/hacktoberfest/

**Comment by paxcema** [comment]
Hey @mrandri19, that's great! 

By all means, feel free to work on this. I will assign you to this issue preemptively, though note that others can also participate, concurrently.

As stated in the original post, we look forward to any questions or implementation ideas you might have. Good luck!

**Comment by hakunanatasha** [comment]
Looking forward : ) feel free to ping one of us (or all of us) if you need anything - we're happy to help!

**Comment by paxcema** [comment]
That sounds nice! We're always open to discuss collaborations :)

The suggested approach sounds all right to me. My only concern is as follows: for convenience in the mixer step, the ideal output representation should be one-dimensional (that is, a single vector per single audio input). Ideally, there should be some aggregation step so that the final encoding that stems from the spectrogram transformation is, indeed, 1D. 

Any ideas on how to achieve this? I can think of learned 2D->1D transformations, but maybe there are simpler options (@George3d6 or @hakunanatasha feel free to chime in).
