### ISSUE TITLE
`Img2VecEncoder` cannot be instantiated

### ISSUE THREAD

**Issue by mrandri19** [mindsdb/lightwood#616]
## Your Environment
* Python version: Python 3.8.10
* Operating system: Ubuntu 20.04.3 LTS
* Lightwood version: 1.3.0

## Describe your issue
`Img2VecEncoder` cannot be instantiated

## How can we replicate it?
* What was the code you ran
```
(venv) ➜  lightwood git:(staging) ✗ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightwood
>>> lightwood.encoder.image.Img2VecEncoder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrea/lightwood/lightwood/encoder/image/img_2_vec.py", line 14, in __init__
    self.aim = aim
NameError: name 'aim' is not defined
```

## Proposed solution

Comment out `self.aim` for now, in the future this can be used to choose the model for example. Perhaps speed will use a light model like `resnext-50-small`  while accuracy can use a bigger one like `vgg` or `resnet101`

---

Edit: also `vec_arr` is missing, I don't want to create another issue just for this. The fix is just to define it: `vec_arr = []`.

**Comment by paxcema** [comment]
## Additional rewards :1st_place_medal: 

The PR to this issue brings 2️⃣ points for entry into the draw for a :computer:  Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag :shirt: :bear: .  For more info check out https://mindsdb.com/hacktoberfest/
