### ISSUE TITLE
`Img2VecEncoder` calls `self.prepare` twice

### ISSUE THREAD

**Issue by mrandri19** [mindsdb/lightwood#618]
## Your Environment
* Python version: Python 3.8.10
* Operating system: Ubuntu 20.04.3 LTS
* Lightwood version: 1.3.0

## Describe your issue
`Img2VecEncoder` crashes when `.encode(images)` is called.

Internally there seems to be some confusion on what the `.prepare` method actually does.
For some reason it is called to convert images to tensors, while in reality it should be used to initialize the model and (maybe) perform some initial training.

## Fixing the issue

Implement a method to convert images to torch tensors.

**Comment by paxcema** [comment]
Agreed, not sure when this behavior was introduced but calling `.prepare()` inside `.encode()` is not correct.

It is should as you put it:
* `prepare()` train/finetune the CNN with all training images
* `encode()` pass an image (or a batch of them) to the trained CNN and obtain encoded descriptor(s) 

Will aim to review #619 tomorrow, along with assigning hacktoberfest points to this and #616 (as per #615); thanks for the help!
