### ISSUE TITLE
:wrench: Implement a `MeanEnsemble` for numerical tasks

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#655]
## Introduction

Lightwood is an AutoML library that aims at abstracting common procedures in the Machine Learning workflow (e.g. data preparation, feature engineering, model building, model analysis) with an approach that can be fully automated but easily customizable and extended thanks to its flexibility. 

One of the key components in model building are "mixers", models that intake features and learn to predict the target column. For any given predictive task, there might be a number of valid mixers that will get trained.

After all mixers are trained, the [`BaseEnsemble`](https://github.com/mindsdb/lightwood/blob/staging/lightwood/ensemble/base.py) abstraction enables ML practitioners to aggregate the predictions of all mixers as they deem convenient.

For example [`BestOf`](https://github.com/mindsdb/lightwood/blob/staging/lightwood/ensemble/best_of.py), the only currently available ensemble, is a simple procedure that evaluates all models and selects the best one based on validation accuracy. 

## Task

In this task, we seek to implement a `MeanEnsemble` for numerical targets. Simply put, it should obtain the predictions of all internal mixers, then output the mean of all predicted values.

## Steps :male_detective: :female_detective: 

- Fork the Lightwood repository, checkout the `staging` branch and from it create a new one.
- Implement the `MeanEnsemble` class. Any files should be added inside the `lightwood/ensemble/` directory.
- Implement a test where your ensemble is successfully used with a sample regression task, like [concrete strength](https://github.com/mindsdb/lightwood/blob/staging/tests/data/concrete_strength.csv). For guidance on how to trigger your custom ensemble, you can check out `Step 3` in the [custom mixer tutorial](https://lightwood.io/tutorials/custom_mixer/custom_mixer.html) (same idea, but you would modify the `.ensemble` key instead).
- Make the PR and address any comments that reviewers might make.

## Additional rewards :1st_place_medal: 

Accepted PRs for ensemble challenges bring :five: points for entry into the draw for a :computer:  Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag :shirt: :bear: .  For more info check out https://mindsdb.com/hacktoberfest/

**Comment by shilpeegupta14** [comment]
hi @paxcema  I would like to do this. Please assign this task to me.
