### ISSUE TITLE
Add new mixers that improve accuracy on the benchmark suite

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#656]
## Task

Lightwood's core component is the mixer, which takes in tensor inputs from the encoders and outputs an encoded representation of the target.

Lightwood ensembles multiple mixers (by default it just picks the best), thus having more reliable mixers can help improve our accuracy in certain scenarios.

This task involves implement *any* mixers which you think can improve lightwood's accuracy. A PR will be accepted as long as the relative accuracy is increased by at least 1% with no modifications other than adding the new mixer and using it in `json_ai.py`.

Multiple people can try this PR assuming no plagiarism between the designs. Keep in mind runtime, ideally try to keep it below or comparable to that of our `Neural` mixer, though we may waive this requirement for exceptionally accurate mixers.

## Steps :male_detective: :female_detective: 

- Fork the Lightwood repository, checkout the `staging` branch and from it create a new one.
- Implement your custom mixers and edit the `api/json_ai.py` file to include it in the list of default mixers
- Run the benchmarks following the instructions [here](https://github.com/mindsdb/benchmarks)
- Note: If you can't afford to run all the benchmarks, test on a subset of small datasets you think your mixer is good at using `--datasets=x,y,z` | Alternatively, contact us (or make a PR) and we will provide compute for you to do this.
- Make the PR and address any comments that reviewers might make.

**Comment by Ryan-Maia** [comment]
Can you assign it to me?

**Comment by paxcema** [comment]
Closing for now.
