### ISSUE TITLE
 Add new ensembles that improve accuracy on the benchmark suite

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#659]
## Task

Lightwood's core component is the encoder, which takes the predictions from the mixers and combines the final prediction.

This task involves implementing *any* ensemble which you think can improve lightwood's accuracy. A PR will be accepted as long as the relative accuracy is increased by at least 1% with no modifications other than adding the new ensembles and using it in `json_ai.py`.

Multiple people can try this PR assuming no plagiarism between the designs.

## Steps :male_detective: :female_detective: 

- Fork the Lightwood repository, checkout the `staging` branch and from it create a new one.
- Implement your custom ensemble and edit the `api/json_ai.py` file to replace the `BestOf` ensemble
- Run the benchmarks following the instructions [here](https://github.com/mindsdb/benchmarks)
- Note: If you can't afford to run all the benchmarks, test on a subset of small datasets you think your ensemble is good at using `--datasets=x,y,z` | Alternatively, contact us (or make a PR) and we will provide compute for you to do this.
- Make the PR and address any comments that reviewers might make.

**Comment by paxcema** [comment]
Closing for now.
