### ISSUE TITLE
Start training on a sub-set

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#67]
Instead of training on the whole dataset at once, start training on a small sub-set (say, as large as 5 or so batches) and as the network start converging on that subset start feeding it the whole dataset (or a bigger sub-set).

This sort of "priming" might help us achieve convergence quicker, which could be rather good considering 0.11.8 increased training times.

**Comment by torrmal** [comment]
closing this issue as we probably want to do n fold cross validation instead
