### ISSUE TITLE
Add test coverage analysis that tracks testing progression in every PR

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#671]
We want to be able to tell, in an automated fashion, that each PR has full test coverage for whatever it introduces.

This is somewhat difficult *but* it can be roughly done the following way:

1. Add a global test coverage analysis that saves the results <somewhere>
2. Save results each time we merge something into staging
3. Whenever a new PR is made at a github action that checks this database for the latest/highest test coverage and makes sure the total test coverage on the PR is greater or equal to that

Ideally <somewhere> is either s3, or, even better, a file in the repository itself, so we don't have to bother with credentials of any sort.

**Comment by paxcema** [comment]
Closing for now.
