### ISSUE TITLE
Unexpected `nan` cleaning behavior

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#674]
[This line](https://github.com/mindsdb/lightwood/blob/353e37970dbf610b14fdf932ee9b10eed194f5a0/lightwood/data/cleaner.py#L55) in `lightwood/data/cleaner.py`:

```python
data[col] = data[col].replace(to_replace=VALUES_FOR_NAN_AND_NONE_IN_PANDAS, value=None)
```

Has an unexpected behavior, where `nan`s are seemingly replaced with a forward fill mode instead of imputed with `None`s.

**Comment by George3d6** [comment]
Closing, should be handled in #700 , doing this it too hard. You can replace `is None` checks with the `is_none` helper when referring to a cell from a pd Series.
