### ISSUE TITLE
Fix LGBM GPU Issue

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#730]
Right now LGBM breaks on the GPU with some bin-size related error (observed on wd dataset), I expect the same one as the one reported here and the related issue: https://github.com/microsoft/LightGBM/issues/3339, since it's the same error log

Based on #729 we need to figure out if the fix here is:

1. Find a way to force CPU LGBM and/or warn the user to uninstall GPU if they have it
2. Find a way to get GPU LGBM to work in lightwood (e.g. splitting columns into multiple values(?))
3. Contribute a fix to the LGBM package itself

Most people don't have LGBM GPU installed and lightwood installs the CPU version, so not too urgent, especially since GPU will still work with most datasets.

**Comment by paxcema** [comment]
Closing, LGBM is working on GPU instances if built from source via #944.
