### ISSUE TITLE
ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' 

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#75]
**Describe the bug**
Installing the latest version of lightwood throws ImportError. I guess the issue is related to the sciki-learn.

**To Reproduce**
1. Train model, the issue is not related to a specific dataset
2. See error

>     from cesium import featurize
>   File "/home/zoran/MyProjects/lightwood/l/lib/python3.7/site-packages/cesium-0.9.9-py3.7-linux-x86_64.egg/cesium/featurize.py", line 10, in <module>
>     from sklearn.preprocessing import Imputer
> ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' (/home/zoran/MyProjects/lightwood/l/lib/python3.7/site-packages/scikit_learn-0.22rc3-py3.7-linux-x86_64.egg/sklearn/preprocessing/__init__.py)

**Screenshots**
![Screenshot from 2019-12-02 14-40-15](https://user-images.githubusercontent.com/7192539/70136664-b9ffc100-168c-11ea-8392-084beab3832e.png)

**Comment by ZoranPandovski** [comment]
This is related with pip installing latest verzion of scikit-learn which was pre-release 0.22rc3 version. We should use fixed version that works 0.21.3. I will create PR

**Comment by ZoranPandovski** [comment]
A new scikit-learn version 0.22 was released yesterday, but there are other errors with using that version. We should keep on 0.21.3 for now.

**Comment by ZoranPandovski** [comment]
Fixed by #74

**Comment by AnasK95** [comment]
from sklearn.impute import SimpleImputer will work because of the following 

DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.

**Comment by subhashi** [comment]
Thank you @AnasK95 It worked.

So I had to use, 

```
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
```

instead of 

```
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
```

Otherwise, it gives the following error.

```
from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'
```

**Comment by kvtheckrock** [comment]
Thanks @AnasK95 and @subhashi 
It worked for me as well.

**Comment by akjha3314** [comment]
thanks it works

**Comment by mh-shifat** [comment]
but 'axis' is no more a argument there ! btw tahnks @AnasK95

**Comment by harmeshm** [comment]
Thank you @AnasK95.

**Comment by Rawkush** [comment]
Thank you @AnasK95 It worked.
 but how do we use axis argument functionality now?

**Comment by MutumaIan** [comment]
Thanks a lot.

**Comment by diegoecon-ai** [comment]
Sincerely thanks! @AnasK95

**Comment by Norni** [comment]
Thanks @subhashi

**Comment by ahmedtamam721** [comment]
i try to upgrade it but !!!

![siket learn](https://user-images.githubusercontent.com/37932386/77471106-691dff00-6e1a-11ea-8f3c-b00d109de499.PNG)

**Comment by Deepak-prog777** [comment]
hey, In version 0.22.2,
for error: ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' (C:\Users\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

You can use this snippet, and it will work fine:
(C:\Users\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

from .imputation import Imputer 

__all__ = [
.
.
.

    'Imputer',             #  type 'imputer'

.
.
.
]
<------------------------------------------------------------->
Hope this would help
<------------------------------------------------------------>
full  __init__.py code here:

"""
The :mod:`sklearn.preprocessing` module includes scaling, centering,
normalization, binarization and imputation methods.
"""

from ._function_transformer import FunctionTransformer

from .data import Binarizer
from .data import KernelCenterer
from .data import MinMaxScaler
from .data import MaxAbsScaler
from .data import Normalizer
from .data import RobustScaler
from .data import StandardScaler
from .data import QuantileTransformer
from .data import add_dummy_feature
from .data import binarize
from .data import normalize
from .data import scale
from .data import robust_scale
from .data import maxabs_scale
from .data import minmax_scale
from .data import quantile_transform
from .data import power_transform
from .data import PowerTransformer
from .data import PolynomialFeatures

from ._encoders import OneHotEncoder
from ._encoders import OrdinalEncoder

from .label import label_binarize
from .label import LabelBinarizer
from .label import LabelEncoder
from .label import MultiLabelBinarizer

from ._discretization import KBinsDiscretizer

from .imputation import Imputer


__all__ = [
    'Binarizer',
    'FunctionTransformer',
    'Imputer',
    'KBinsDiscretizer',
    'KernelCenterer',
    'LabelBinarizer',
    'LabelEncoder',
    'MultiLabelBinarizer',
    'MinMaxScaler',
    'MaxAbsScaler',
    'QuantileTransformer',
    'Normalizer',
    'OneHotEncoder',
    'OrdinalEncoder',
    'PowerTransformer',
    'RobustScaler',
    'StandardScaler',
    'add_dummy_feature',
    'PolynomialFeatures',
    'binarize',
    'normalize',
    'scale',
    'robust_scale',
    'maxabs_scale',
    'minmax_scale',
    'label_binarize',
    'quantile_transform',
    'power_transform',
    'Imputer'
]

**Comment by Yassir-Alharbi** [comment]
This was sorted by,
https://github.com/scikit-learn/scikit-learn/issues/16152

**Comment by jhhalls** [comment]
> This is related with pip installing latest verzion of scikit-learn which was pre-release 0.22rc3 version. We should use fixed version that works 0.21.3. I will create PR

How do i downgrade scikit-learn from 0.22.2 to 0.21

**Comment by vardhan7293** [comment]
> Thank you @AnasK95 It worked.
> 
> So I had to use,
> 
> ```
> from sklearn.impute import SimpleImputer 
> imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
> ```
> 
> instead of
> 
> ```
> from sklearn.preprocessing import Imputer
> imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
> ```
> 
> Otherwise, it gives the following error.
> 
> ```
> from sklearn.preprocessing import Imputer
> ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'
> ```

**Comment by vardhan7293** [comment]
Thanks @AnasK95  and @subhashi  it helps 
Cheers to all who are in hadelin machine learning course

**Comment by ambujbhargava** [comment]
For me I used SimpleImputer

from sklearn.impute import SimpleImputer

worked.

**Comment by rohitbajpai1** [comment]
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
X.fit[:, 1:3] = imputer.fit_transform(X[:, 1:3])
X = X.apply(lambda x: x.fillna(x.value_counts().index[0]))

(slice(None, None, None), slice(1, 3, None))' is an invalid key

Still getting this error

**Comment by sudhirp93** [comment]
ImportError: cannot import name 'MinMaxScalar' from sklearn.preprocessing ....
any help?

**Comment by PatChandresh** [comment]
I used 
**from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(strategy='median')**

instead of 
**from sklearn.preprocessing import Imputer
imputer = Imputer(strategy="median")**

not throwing any error

**Comment by arefehsajedi** [comment]
Hey there,

I just confronted similar error, and I found out the reason was version of the sciki-learn..
in the latest version , you should code as :
from sklearn.**impute** import **SimpleImputer**
instead of : 
from sklearn.**preprocessing** import **SimpleImputer**

also note that inputs are as following: 
SimpleImputer(**missing_values**=np.**nan**, strategy='mean')

also regarding using np, you should summon numpy library.
besides, there is no required parameter as **axis=0 or 1**
