### ISSUE TITLE
Deprecate psutil

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#777]
- Psutil is only used once, I think we can replace it with os/sys functions, it's very annoying to install on MacBook and it's gigantic, we should try removing it

**Comment by George3d6** [comment]
Also allows moving PILLOW to `requirements_image.txt` which is wonderful since PILLWO is horribel

**Comment by paxcema** [comment]
Had a quick look into this. Apparently, `os` methods would have to use `free` internally, making them linux-only.

**Comment by paxcema** [comment]
Closing for now.
