### ISSUE TITLE
GIT QUESTIONS/doubts for new entries

### ISSUE THREAD

**Issue by ITACHI8765** [mindsdb/lightwood#821]
Which four states can be applied to a commit using the GitHub status API

**Comment by paxcema** [comment]
Hello @ITACHI8765,

As far as I know, our CI does not mark commits with any such tag. For development purposes, we are loosely based on the guide proposed by [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). Can I ask _why_ are you interested in this?

**Comment by ITACHI8765** [comment]
Just starting with a new software..
yet to go
as a duo 
with my bro

**Comment by paxcema** [comment]
I see. If you are getting started and are interested in contributing to Lightwood, be sure to check out our [contributor's guide](https://github.com/mindsdb/lightwood#contribute-to-lightwood).

I will be closing this issue now, but feel free to open additional issues if you need help.
