### ISSUE TITLE
Overflow in `home_rentals` predictions

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#837]
## Describe your issue

As reported by @Ricram2, a predictor trained on home rentals may overflow and return incorrect predictions. This has been an issue in the past, and (seemingly not) solved in #574:

![image](https://user-images.githubusercontent.com/12536303/152922449-ed84746d-9593-42b7-a022-9c3dad7ada59.png)

**Comment by paxcema** [comment]
See also [mindsdb#1981](https://github.com/mindsdb/mindsdb/issues/1981)

**Comment by George3d6** [comment]
Using Ridge regression (l2 norm to penalize gigantic coefficients) fixes this, tested /w mindsdb where the overflow happens by setting:

`encoders.location.module='CategoricalAutoEncoder', model.args.submodels='[{"module":"Regression", "args":{"stop_after": 500}}]'` and results look normal

Will make PR, closing this
