### ISSUE TITLE
Add `export` method that saves both `Predictor` object and its code.

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#852]
Respectively, `import` should load the predictor+code.

**Comment by gwild** [comment]
def save_predictors(self,tag=""):
        for i, predictor in enumerate(self.predictors):
            predictor.save("predictors/"+str(self.targets[i])+tag)
        for i, code in enumerate(self.codes):
            with open("code/"+str(self.targets[i])+"_code"+tag, "wb") as fp:
                dill.dump(self.codes[i], fp)

    def load_predictors(self,tag=""):
        predictors = []
        predictor_files = sorted(glob.glob('predictors/'+'*'+tag))
        code_files = sorted(glob.glob('code/'+'*'+tag))
        print('predictors:', predictor_files)
        print('predictors loaded')
        for i, predictor in enumerate(predictor_files):
            with open(code_files[i], 'rb') as fp:
                code = dill.load(fp)
            predictors.append(predictor_from_state(predictor, code))
        self.predictors = predictors
        self.tag = tag

**Comment by TalaatHasanin** [comment]
Is this still on demand @paxcema ?

**Comment by paxcema** [comment]
Hi @TalaatHasanin, yes it is :)

If you want to try your hand at it, we can assign you. Feel free to ask Amy questions regarding design or implementation of this.

**Comment by TalaatHasanin** [comment]
Now I'm installing the package to try it and try to understand.
if there is anything to learn or read about the implementation I would be vey grateful ?

**Comment by noraa-july-stoke** [comment]
Hey was thinking about looking into this issue. But I was wondering if I can get a reference to the relevant file where this should be implemented?

**Comment by noraa-july-stoke** [comment]
Would it be predictor.py?

**Comment by paxcema** [comment]
Hi @noraa-july-stoke,

Yes, that `save()` method is close to what we're after, although not exactly. Please open a pull request and we can provide specific feedback on what's missing or should change.

**Comment by noraa-july-stoke** [comment]
ok will do it, im assuming you want me to use that code_to_json_ai  and use the value returned from it instead?
i'll go ahead and make that change and submit PR thank you
