### ISSUE TITLE
Improve documentation of device-related methods and docs regarding GPU usage

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#909]
At the moment the policy to trigger GPU usage (and advanced features like AMP) is not clear when reading the documentation.

**Comment by TalaatHasanin** [comment]
I want more information about what exactly I will write in this section? @paxcema

**Comment by paxcema** [comment]
I'm not sure this is an ideal "good first issue". Regardless, I'd recommend that you take a close look at both the `lightwood.helpers.device` module and the `lightwood.helpers.torch.LightwoodAutocast` module, then search for their usage throughout the repo.

The ideal Pull Request would add informative docstrings to the classes and methods above where missing, explaining how, when and why are GPUs leveraged when using Lightwood.

**Comment by paxcema** [comment]
Hi, I think the comment above summarizes it. Essentially, take a look at the code and document what it is doing as you understand it (doesn't have to be perfect, we can adjust it in the PR process).
