### ISSUE TITLE
Neural Mixer: Evaluate, refactor or redesign where necessary, unit test, and document

### ISSUE THREAD

**Issue by fromdavelewis** [mindsdb/lightwood#916]

**Comment by paxcema** [comment]
As reported by @tomhuds we need to take a closer look at the efficiency after selecting initial hyperparams, seems to scale poorly.

**Comment by tomhuds** [comment]
@paxcema can we close?

**Comment by paxcema** [comment]
Still relevant, will be worked on by @pafluxa and I at some point in the coming weeks.

**Comment by paxcema** [comment]
Ok, closing now. We can still improve but the mixer is at a better place in terms of speed/accuracy tradeoff now.
