### ISSUE TITLE
Design and plan (create issues) to make  Lightwood independent and run tests on itself

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/lightwood#922]

**Comment by paxcema** [comment]
Here's a list for reference:
1. Add `mindsdb` and `mindsdb_sql` as dependencies for the handler.
2. Remove direct/hardcoded usage of `lightwood` within `mindsdb`. This involves: 
a. Remove `lightwood` as dependency from `mindsdb`
b. Replace direct `lightwood` usage from `interfaces/model/learn_process` with generic handler calls
c. Replace direct `lightwood` usage from `api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode` with generic predictive handler behavior
d. Replace direct `lightwood` usage from `interfaces/model/model_controller` with generic handler calls
e. Replace direct `lightwood` usage from `api/mysql/mysql_proxy/mysql_proxy` with generic predictive handler behavior


I'll be opening issues for both these points, so we can close this issue.
