### ISSUE TITLE
Investigate additional anomaly detection approaches

### ISSUE THREAD

**Issue by tomhuds** [mindsdb/lightwood#923]
Some possible approaches

**1. Fine-tuning model using labels to minimise incorrect labels**
- Take a column which has the anomalies
- Either incorporate this in the main model training, or just add into analysis block

**2. Incorporate new techniques during analysis block, e.g.**
- A block that is trained on the Anomaly label
- Their own rule-based custom block, which we can help to develop
- STL
- …

**Comment by paxcema** [comment]
I will close this for now, as we have since added #983
