### ISSUE TITLE
Decide on best evaluation metrics for timeseries

### ISSUE THREAD

**Issue by tomhuds** [mindsdb/lightwood#924]
Especially for with horizon>1 
Is current evaluate_num_array_accuracy the best?

**Comment by paxcema** [comment]
Made changes to use the bounded variant by default. It internally uses `evaluate_num_array_accuracy`, however, it's been changed to have truly "naive" forecasts for the scaling error computation, as recommended [here](https://arxiv.org/abs/2203.10716). 

Let's try it out, see how it goes, and we can reopen this one if need be.
