### ISSUE TITLE
Experiment with/without Autoencoder for feature engineering

### ISSUE THREAD

**Issue by tomhuds** [mindsdb/lightwood#925]
Ref slack conversation: https://mindsdb.slack.com/archives/C017QKWABUY/p1656488084218559

Points to consider
- Get a selection of datasets to test (after they have been 'encoded' by lightwood)
- Could evaluate: no autoencoder features, only autoencoder features, original + autoencoder features
- Autoencoder would likely need to be at the mixer level
- Would probably only work if there was 'lots' of data?

**Comment by paxcema** [comment]
Handled by #1163
