### ISSUE TITLE
TabTransformers as mixers

### ISSUE THREAD

**Issue by tomhuds** [mindsdb/lightwood#926]
Ref slack conversation: https://mindsdb.slack.com/archives/C017QKWABUY/p1656838359151799

Points to consider
- How to use them
- Could they be a mixer for regression/classification
- Performance vs others

**Comment by paxcema** [comment]
Seems like we can fit it perfectly within the mixer abstraction.

A starting point would be to adapt this [tutorial](https://keras.io/examples/structured_data/tabtransformer/) to instead use data encoded from our encoder phase.
