### ISSUE TITLE
Weird segfault issue on import

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#95]
Basically, there's a weird segfault happening when importing lightwood... in some cases.

Examples:
```
Segmentation fault:
import transformers

Segmentation fault:
import mindsdb
import lightwood

Segmentation fault:
import mindsdb
import transformers

Works:
import lightwood
import transformers

Works:
import lightwood
import mindsd
```
Doesn't happen on all machine. No idea of the cause, investigating now.

**Comment by George3d6** [comment]
By a weird stroke of luck, this bug is fixed if lightwood is imported before mindsdb... which we now do in the `__init__.py` of mindsdb. So all the cases in which the segfault happens have been fixed.

The reason as to why this is the case though...  I still do not know that :/

Leaving the issue open, though maybe it should be mindsdb related.

**Comment by George3d6** [comment]
So, some extra help here: https://github.com/pytorch/pytorch/issues/4111

Also, interesting that this crashes:

```
>>> import sklearn
>>> import torchvision
```

Might be an issue related to the latest torch/trochvision release.

**Comment by George3d6** [comment]
It seems like a good way of fixing this is making sure that  `torchvision` is always imported first and foremost, that fixes all other crashes seemingly.

**Comment by George3d6** [comment]
Note: Check whether the new torch/torchvision version fixes this on all environments.

**Comment by ZoranPandovski** [comment]
@George3d6 Sure, I will add update if something popsup.

**Comment by George3d6** [comment]
Should be fixed now.
