### ISSUE TITLE
NLP Encoders

### ISSUE THREAD

**Issue by torrmal** [mindsdb/lightwood#96]
lets add support for the following simple text encoders:
N-gram frequency / TFIDF followed by Truncated SVD
N-gram frequency / TFIDF followed by Linear / Logistic regression

see this resource as a benchmark

https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/dai/rel-1.8.1-143/docs/userguide/nlp.html#nlp-in-dai

**Comment by George3d6** [comment]
So the idea would be to have ngram/TFIDF + SVD/LR predict the target variables directly and feed that into the mixer, correct ? (similar to what we do now for numerical/categorical values with the BERT encoder)

**Comment by torrmal** [comment]
yes

**Comment by George3d6** [comment]
This is being done by the BERT/DISTIL-BERT/GPT2 text encoder now, so, closing, not sure why it remained open.
