### ISSUE TITLE
Move data analysis into separate library

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#999]
This may include a lot of components. Exact scope is still pending.

**Comment by paxcema** [comment]
Hi @thebhavana, yes. The idea is to move parts of Lightwood's pipeline into separate libraries that don't require as many dependencies, and can be called from other packages like MindsDB proper without requiring e.g. torch.

One good working example of this is `mindsdb/type_infer`, which replaces the internal type inference logic (see `lightwood:use_typeinfer` in #1024).

However, I can't assign you this, as the core team will be working on it. Be on the lookout for once it's completed, as we will post lots of good first issues to get the new packages up to speed! ⚡

**Comment by thebhavana** [comment]
Okay @paxcema

**Comment by paxcema** [comment]
Fixed in #1049.
